import { PERMISSIONS } from './permissions';

export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  POS: '/point-of-sale',
  INVENTORY: '/inventory',
  PRODUCTS: '/products',
  PURCHASES: '/purchases',
  CATEGORIES: '/categories',
  BRANDS: '/brands',
  ATTRIBUTES: '/attributes',
  SUPPLIERS: '/suppliers',
  USERS: '/users',
  ROLES: '/roles',
  REPORTS: '/reports',
  ACTIVITY_LOGS: '/activity-logs',
  SETTINGS: '/settings'
};

export const routePermissions = {
  [ROUTES.DASHBOARD]: PERMISSIONS.DASHBOARD,
  [ROUTES.POS]: PERMISSIONS.POS,
  [ROUTES.INVENTORY]: PERMISSIONS.INVENTORY,
  [ROUTES.PRODUCTS]: PERMISSIONS.PRODUCTS,
  [ROUTES.PURCHASES]: PERMISSIONS.PURCHASES,
  [ROUTES.CATEGORIES]: PERMISSIONS.CATEGORIES,
  [ROUTES.BRANDS]: PERMISSIONS.BRANDS,
  [ROUTES.ATTRIBUTES]: PERMISSIONS.ATTRIBUTES,
  [ROUTES.SUPPLIERS]: PERMISSIONS.SUPPLIERS,
  [ROUTES.USERS]: PERMISSIONS.USERS,
  [ROUTES.ROLES]: PERMISSIONS.ROLES,
  [ROUTES.REPORTS]: PERMISSIONS.REPORTS,
  [ROUTES.ACTIVITY_LOGS]: PERMISSIONS.LOGS,
  [ROUTES.SETTINGS]: PERMISSIONS.SETTINGS
};

